language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install .
script:
  - python -m pytest .
